# Generated by Django 2.2.4 on 2020-09-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellite', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='bookingStatus',
            field=models.CharField(choices=[('pending', 'En Cours'), ('rejected', 'Rejeté'), ('invoiced', 'Approuvé')], default='pending', max_length=6),
        ),
    ]
